main:
  params: [input]
  steps:
    - init:
        assign:
          - recipe_id: ${uuid.generate()}
    - call_gemini:
        call: googleapis.aiplatform.v1.projects.locations.endpoints.generateContent
        args:
          model: "projects/sascha-playground-doit/locations/us-central1/publishers/google/models/gemini-1.5-pro-001"
          region: "us-central1"
          body:
            contents:
              role: user
              parts:
                - text: ${input.recipePrompt}
            safety_settings:  # optional
              category: HARM_CATEGORY_DANGEROUS_CONTENT
              threshold: BLOCK_ONLY_HIGH
            generation_config:  # optional
              temperature: 0.2
              maxOutputTokens: 2000
              topK: 10
              topP: 0.9
              responseMimeType: application/json
              responseSchema:
                type: object
                properties:
                  recipe_title:
                    type: string
                    description: The recipe title.
                  recipe_description:
                    type: string
                    description: The recipe description.
                  recipe_image_prompt:
                    type: string
                    description: The prompt to generate the recipe image.
                  ingredients:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the ingredient.
                        quantity:
                          type: string
                          description: The quantity of the ingredient.
                        unit:
                          type: string
                          description: The unit of measurement for the ingredient.
                      required:
                        - name
                        - quantity  # Adjust required fields as needed
                required:
                  - recipe_title
                  - recipe_description
                  - recipe_image_prompt
        result: gemini_response
    - parse_json_recipe:
        assign:
          - parsed_recipe: '${json.decode(gemini_response.candidates[0].content.parts[0].text)}'
          - recipe_image_prompt: '${parsed_recipe.recipe_image_prompt}'
          - usage_metadata: ${gemini_response.usageMetadata}
    - upload_recipe_to_gcs:
        call: googleapis.storage.v1.objects.insert
        args:
          bucket: "doit-llm"
          uploadType: "media"
          name: ${"recipes/" + recipe_id + ".json"}
          body:   '${json.encode(parsed_recipe)}'
    - generate_image:
        call: http.post
        args:
          url: "https://image-generation-xgdxnb6fdq-uc.a.run.app"
          body:
            uuid: ${recipe_id}
            prompt: ${recipe_image_prompt}
        result: image_generation_response
    - returnStep:
        return:
          recipe: ${parsed_recipe}
          image_generation_response: ${image_generation_response}
          usage_metadata: ${usage_metadata}