main:
  params: [input]
  steps:
    - call_gemini:
        call: googleapis.aiplatform.v1.projects.locations.endpoints.generateContent
        args:
          model: "projects/sascha-playground-doit/locations/us-central1/publishers/google/models/gemini-1.5-pro-001"
          region: "us-central1"
          body:
            contents:
              role: user
              parts:
                - text: ${input.recipePrompt}
            safety_settings:  # optional
              category: HARM_CATEGORY_DANGEROUS_CONTENT
              threshold: BLOCK_ONLY_HIGH
            generation_config:  # optional
              temperature: 0.2
              maxOutputTokens: 2000
              topK: 10
              topP: 0.9
              responseMimeType: application/json
              responseSchema:
                type: object
                properties:
                  recipe_title:
                    type: string
                    description: The recipe title.
                  recipe_description:
                    type: string
                    description: The recipe description.
                  ingredients:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the ingredient.
                        quantity:
                          type: string
                          description: The quantity of the ingredient.
                        unit:
                          type: string
                          description: The unit of measurement for the ingredient.
                      required:
                        - name
                        - quantity  # Adjust required fields as needed
                required:
                  - recipe_title
                  - recipe_description
        result: gemini_response
    - parse_json_recipe:
        assign:
          - parsed_recipe: '${json.decode(gemini_response.candidates[0].content.parts[0].text)}'
    - upload_recipe_to_gcs:
        call: googleapis.storage.v1.objects.insert
        args:
          bucket: "doit-llm"
          uploadType: "media"
          name: ${"recipes/" + uuid.generate() + ".json"}
          body:   '${json.encode(parsed_recipe)}'
    - returnStep:
        return: ${gemini_response.candidates[0].content.parts[0].text}